server:
  port: 8855

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    dynamic:
      primary: cart
  redis:
    cluster:
      nodes: 127.0.0.1:8001,127.0.0.1:8002,127.0.0.1:8003,127.0.0.1:8004,127.0.0.1:8005,127.0.0.1:8006
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
feign:
  client:
    config:
      default:
        loggerLevel: full
        requestInterceptors:
          - com.gw.gwmall.cart.feignapi.interceptor.HeaderInterceptor
        readTimeout: 3000
        connectTimeout: 3000