logging:
  level:
    com:
      gw:
        gwmall:
          history:
            dao: debug


spring:
  #读写分离配置
  shardingsphere:
    #数据源配置
    datasource:
      names: ds-master,ds-slave
      ds-master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/tl_mall_order?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        initialSize: 5
        minIdle: 10
        maxActive: 30
        validationQuery: SELECT 1 FROM DUAL
        username: root
        password: wu123
      ds-slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/tl_mall_order?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
        initialSize: 5
        minIdle: 10
        maxActive: 30
        validationQuery: SELECT 1 FROM DUAL
        username: root
        password: wu123
    #读写分离配置
    masterslave:
      name: ds_ms
      master-data-sourceName: ds-master
      slave-data-sourceNames:
        - ds-slave
      load-balance-algorithmType: ROUND_ROBIN
    props:
      sql:
        show: true