server:
  port: 8867
spring:
  application:
    name: gw-product

  datasource:
    dynamic:
      primary: goods
  redis:
    custom:
      string:
        redistemplate:
          enable: true
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:9191
      datasource:
        flow-rules:
          nacos:
            serverAddr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            dataType: json
            ruleType: flow
        degrade-rules:
          nacos:
            serverAddr: 127.0.0.1:8848
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            dataType: json
            ruleType: degrade
        param-flow-rules:
          nacos:
            serverAddr: 127.0.0.1:8848
            dataId: ${spring.application.name}-param-flow-rules
            groupId: SENTINEL_GROUP
            dataType: json
            ruleType: param-flow
        authority-rules:
          nacos:
            serverAddr: 127.0.0.1:8848
            dataId: ${spring.application.name}-authority-rules
            groupId: SENTINEL_GROUP
            dataType: json
            ruleType: authority
        system-rules:
          nacos:
            serverAddr: 127.0.0.1:8848
            dataId: ${spring.application.name}-system-rules
            groupId: SENTINEL_GROUP
            dataType: json
            ruleType: system

mybatis:
  mapper-locations:
    - classpath:com/**/mapper/*.xml
    - classpath:dao/*.xml

management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

seata:
  tx-service-group: gw-order-group
  application-id: ${spring.application.name}
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: SEATA_GROUP
      server-addr: 127.0.0.1:8848

  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: seata-ns
      group: SEATA_GROUP
      data-id: seataServer.properties

  client:
    support:
      spring:
        datasource-autoproxy: true

logging:
  level:
    com:
      gw:
        gwmall:
          mapper: debug
          dao: debug

rocketmq:
  name-server: 127.0.0.1:9876 #连接超时时间
  gwmall:
    couponConsumerGroup: coupon-give-away-consumer-group #事务消息群组
    transCouponTopic: trans-coupon-topic #

bloomfilter:
  config:
    type: redis-plugin
#    type: guava
    error-rate: "0.0001"
    capacity: 1000000

