server:
  port: 8877

#spring:
#  data:
#    mongodb:
##      host: 218.76.8.107
#      host: 127.0.0.1
#      port: 27017
#      database: micromall
#      password: 123456
#      username: gwmall

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer #JWT负载中拿到开头

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
      orderId: "portal:orderId:"
    expire:
      authCode: 90 # 验证码超期时间


rocketmq:
  name-server: 127.0.0.1:9876 #连接超时时间
  producer:
    send-message-timeout: 30000 #发送消息超时时间
    group: member-producer-group
  gwmall:
    couponConsumerGroup: coupon-give-away-consumer-group #事务消息群组
    transCouponTopic: trans-coupon-topic #

spring:
  # 选择redis为session存储
  session:
    store-type: redis
  data:
    mongodb:
      uri: mongodb://gwmall:123456@127.0.0.1:28017,127.0.0.1:28018,127.0.0.1:28019/test?authSource=admin&replicaSet=gmrs0
