server:
  port: 8054
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tl_mall_goods?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wu123
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

#  data:
#    elasticsearch:
#      repositories:
#        enabled: true
#      cluster-nodes: 127.0.0.1:9300
#      cluster-name: elasticsearch
  application:
    name: gw-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#  data:
#    elasticsearch:
#      rest:
#        uris: 127.0.0.1:9300
#        username: elastic
#        password: 123456


mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml




